"""
Django settings for base project.
Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
import environ
import dj_database_url

# Diretório Base do Projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicialização do ambiente de variáveis seguras (.env)
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ==============================================================================
# CONFIGURAÇÃO DE DIRETRIZ CRÍTICA DE AUTENTICAÇÃO (MANTIDA NO TOPO)
# ==============================================================================
AUTH_USER_MODEL = 'core.UsuarioNexus'

# Chave de segurança
SECRET_KEY = 'django-insecure-5%+5v$$65dq^er(7eev=jwmq!wera_k9j5%gr+-mp2vuco2zzw'

# Modo Debug (Aviso: mude para False antes de colocar o sistema em ambiente de produção final)
DEBUG = True

ALLOWED_HOSTS = [
    'nexus360-qyx7.onrender.com',
    'portalnexus360.onrender.com',
    'localhost',
    '127.0.0.1',
    '.onrender.com',
]

# Aplicativos Instalados
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicativo Core do Sistema Nexus 360
    'core.apps.CoreConfig', 
]

# Middlewares de Segurança e Processamento
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Gerenciador de arquivos estáticos em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'

# ==============================================================================
# CONFIGURAÇÃO DE BANCO DE DADOS (PRODUÇÃO VS DESENVOLVIMENTO)
# ==============================================================================
if os.environ.get('RENDER'):
    # Ambiente de Produção (Render / Linux): Conecta ao PostgreSQL remoto de forma nativa
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
else:
    # Ambiente de Desenvolvimento (Seu Computador / Windows): Usa SQLite local estável
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Validadores de Senha Padrão
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internacionalização e Fusos Horários
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# CONFIGURAÇÕES DE ARQUIVOS ESTÁTICOS (CSS, JS, IMAGENS) - SEM DUPLICIDADE
# ==============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Compactação ultra rápida do WhiteNoise para carregar o visual no Render sem lentidão
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Redirecionamentos de Login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ==============================================================================
# CONFIGURAÇÃO DE ENVIO DE E-MAIL REAL (SMTP VIA VARIÁVEIS DO RENDER)
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Coleta as chaves configuradas na aba "Environment" do seu painel do Render
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER